---
name: Test-More-Behaviours
version: 0.0.2
author:
  - 'Rija Menage <cpan@rijam.sent.as>'
abstract: Group Test::More assertions into behaviours
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
  version: 0
provides:
  Test::More::Behaviours:
    file: lib/Test/More/Behaviours.pm
    version: 0.0.2
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
